.TH SFTAGGER 1 sftagger-VERSION
.SH NAME
sftagger \- simple file tagging tool
.SH SYNOPSIS
.B sftagger
[options] filenames
.SH DESCRIPTION
.B sftagger
is a simple file tagging tool written in C. It allows assigning multiple tags 
to each files/directories, categorising tags, and searching for files based on
the tags assigned per files.
.SH OPTIONS
.TP
.B -n
Creates the file that'll contain the tags database
.TP
.B -r
Outputs the entire file that contains the tags database
.TP
.B -v
Outputs the version of the program
.TP
.B -h
Outputs the usage/synopsis
.TP
.B -s
Outputs the result of the search
.TP
.B -x program
Execute the program specified
.TP
.B categories [TODO]
Outputs the categories and its tags as well as the amount of files has each
tag. Also puts empty categories in the end of output
.TP
.B -a
Allows to add category, tags, and appends tags per files
.RS
.TP
.B -ac
Adds category/categories to the database
.TP
.B -at
Adds tags to the category in the database
.TP
.B -az
Adds tags (specified after entering command) to each files specified
.RE
.TP
.B -e
Allows to rename category, and tags
.RS
.TP
.B -ec
Rename the category specified
.TP
.B -et
Rename the tag specified
.RE
.TP
.B -r
Allows to remove category, tags, tags per files, and files
.RS
.TP
.B -rc
Removes the category specified, warning follows after the command entered
.TP
.B -rt
Removes the tags specified
.TP
.B -rz
Removes the tags (specified after entering command) from the files specified
.TP
.B -rf
Removes the files specified
.RE
.TP
.B -a
Outputs all files
.TP
.B show-tags [TODO]
Outputs the tags (and its category) of the filenames given, as well as amount
of tags each file has
.SH EXAMPLES
.TP
.B sftagger -x "sxiv" -s foo
Search tags then execute it with a program.
Replace "foo" with your searches (can be more than one keyword(s)) and "sxiv"
with your program of choice
.TP
.B -ic gender race
this will add "gender" and "race" as categories

The category command can also be used to create the database file
.TP
.B -it small big size
"small" and "big" are the tags, "size" are the category
.TP
.B -iz "arts plain" *.png
adds the tags "arts" and "plain" to the files that has ".png" in the suffix
.TP
.B -ec bar foo
replaces category "foo" with "bar"
.TP
.B -et bar foo
replaces tag "foo" with "bar"
.TP
.B -rc bread_type
removes category "bread_type"
.TP
.B -rt white brown
removes tags "white" and "brown"
.TP
.B -rz "bread" bread_01.jpg bread_02.jpg

removes the tag "bread" from the files "bread_01.jpg" and "bread_02.jpg"
.TP
.B -rf not_bread_01.jpg not_bread_02.png
removes the files "not_bread_01.jpg" and "not_bread_02.png" from the list
.TP
.B show-tags not_bread_01.jpg bread_01.jpg [TODO]
outputs the tags (and category per tag) for files "not_bread_01.jpg" and 
"bread_01.jpg"
.SH SEE ALSO
.BR xargs (1)
